Repository gpuweb/cts, pull requests merged in 2023-07, with the labels that each got.

#2526 [wgsl] Add workgroup_size validation tests.
  src/webgpu/shader/validation/shader_io/workgroup_size.spec.ts
Labels: wgsl

#2802 Shader uniformity validation tests for functions
  src/webgpu/shader/validation/uniformity/uniformity.spec.ts
Labels: wgsl

#2780 Add support for overflow domains to correctly rounded
  src/unittests/maths.spec.ts
  src/webgpu/util/constants.ts
  src/webgpu/util/math.ts
Labels: wgsl

#2805 Implement f16-based bitcast validation tests
  src/webgpu/shader/validation/expression/call/builtin/bitcast.spec.ts
Labels: wgsl

#2803 wgsl: Add tests for pointer alias analysis
  src/webgpu/shader/validation/functions/alias_analysis.spec.ts
Labels: wgsl

#2811 [wgsl] More invariant parsing tests.
  src/webgpu/shader/validation/shader_io/invariant.spec.ts
Labels: wgsl

#2810 [wgsl] add id validation tests.
  src/webgpu/shader/validation/shader_io/id.spec.ts
Labels: wgsl

#2808 [wgsl] Validate @group and @binding parsing
  src/webgpu/shader/validation/shader_io/binding.spec.ts
  src/webgpu/shader/validation/shader_io/group.spec.ts
  src/webgpu/shader/validation/shader_io/group_and_binding.spec.ts
Labels: wgsl

#2815 [wgsl] More workgroup_size tests.
  src/webgpu/shader/validation/shader_io/workgroup_size.spec.ts
Labels: wgsl

#2817 Function restriction validation tests
  src/webgpu/shader/validation/functions/restrictions.spec.ts
Labels: wgsl

#2804 Validation for uniformity of pointer parameters
  src/webgpu/shader/validation/uniformity/uniformity.spec.ts
Labels: wgsl

#2820 [wgsl] Add more interpolation tests
  src/webgpu/shader/validation/shader_io/interpolate.spec.ts
Labels: wgsl

#2823 [wgsl] Validate no recursion in type aliases
  src/webgpu/shader/validation/types/alias.spec.ts
Labels: wgsl

#2825 [wgsl] Validate no recursion in structure types
  src/webgpu/shader/validation/types/struct.spec.ts
Labels: wgsl

#2831 Validate function declarations
  src/webgpu/shader/validation/functions/restrictions.spec.ts
Labels: wgsl

#2835 [wgsl] Validate no recursion for const/override
  src/webgpu/shader/validation/decl/const.spec.ts
  src/webgpu/shader/validation/decl/override.spec.ts
Labels: wgsl

#2822 [wgsl] Add location validation tests
  src/webgpu/shader/validation/shader_io/locations.spec.ts
Labels: wgsl

#2839 [wgsl] Add validation tests for size attribute.
  src/webgpu/shader/validation/shader_io/size.spec.ts
Labels: wgsl

#2841 Validate function calls
  src/webgpu/shader/validation/functions/restrictions.spec.ts
Labels: wgsl

#2858 Fix size_fp16 test
  src/webgpu/shader/validation/shader_io/size.spec.ts
Labels: bug, wgsl

#2857 De-duplicate resource interface tests
  src/webgpu/shader/validation/resource_interface/bindings.spec.ts
  src/webgpu/shader/validation/resource_interface/util.ts
  src/webgpu/shader/validation/shader_io/group_and_binding.spec.ts
  src/webgpu/shader/validation/shader_io/util.ts
Labels: wgsl

#2794 Update FP documentation
  docs/fp_primer.md
Labels: wgsl

#2861 Validate diagnostics
  src/webgpu/shader/validation/parse/diagnostic.spec.ts
  src/webgpu/shader/validation/shader_validation_test.ts
Labels: wgsl

#2865 Validate @must_use
  src/webgpu/shader/validation/parse/must_use.spec.ts
Labels: wgsl

#2866 Refactor floating_point.spec.ts unittest params
  src/unittests/floating_point.spec.ts
  src/webgpu/util/floating_point.ts
Labels: enhancement, wgsl

#2756 wgsl: Implement AF -> AF assignment tests
  src/webgpu/shader/execution/expression/expression.ts
  src/webgpu/shader/execution/expression/unary/abstract_float_assignment.spec.ts
  src/webgpu/shader/execution/expression/unary/af_assignment.spec.ts
  src/webgpu/util/conversion.ts
Labels: wgsl
